openrouter_api_key: ""
deepseek_model: ""

alpha_vantage_api_key: ""
finnhub_api_key: ""

default_symbol: "AAPL"
default_user_query: "Is this stock worth short-term investment based on current news and chart movement?"

output_chart_path: "charts/latest.png"
